networks:
  default:
    name: hube
    driver: bridge

services:
  backend:
    image: deirofelippe/teste-tecnico-hube:latest
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - './:/home/node/app'
    ports:
      - '3000:3000'
    restart: unless-stopped
    # healthcheck:
    #   test: ['CMD', 'curl', '-f', 'http://localhost:3000/healthz']
    #   interval: 5s
    #   timeout: 5s
    #   retries: 10
    #   start_period: 10s
