networks:
  default:
    name: hube
    driver: bridge

services:
  backend:
    image: deirofelippe/teste-tecnico-hube:latest
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    command: sleep infinity
    volumes:
      - './:/home/node/app'
    ports:
      - '3000:3000'
    restart: unless-stopped
